/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseDialog: typeof import('./components/BaseDialog.vue')['default']
    CustomerTable: typeof import('./components/CustomerTable.vue')['default']
    ErrorDialog: typeof import('./components/ErrorDialog.vue')['default']
    FormDialog: typeof import('./components/FormDialog.vue')['default']
    Information: typeof import('./components/Information.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    ProductTable: typeof import('./components/ProductTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
    TodoCard: typeof import('./components/TodoCard.vue')['default']
  }
}
